<?php 
case "empresa": $title= "Empresa | Clicheria Voluntários"; $description= "Conheça a Clicheria Voluntários. Fundada em 1980 na cidade de São Paulo para oferecer o que há de melhor na gravação de clichês. Clique para mais informações."; break;
case "magnesio": $title= "Magnésio | Clicheria Voluntários"; $description= "Conheça os serviços em magnésio que a Clicheria Voluntários oferece. Clique e confira."; break;
case "zinco": $title= "Zinco | Clicheria Voluntários"; $description= "Conheça os serviços em zinco que a Clicheria Voluntários oferece. Clique e confira."; break;
case "fotolito digital": $title= "Fotolito Digital | Clicheria Voluntários"; $description= "Conheça os serviços em fotolito digital que a Clicheria Voluntários oferece. Clique e confira."; break;
case "fotopolimero": $title= "Fotopolimero | Clicheria Voluntários"; $description= "Conheça os serviços em fotopolimero que a Clicheria Voluntários oferece. Clique e confira."; break;
case "gravacao e corte a laser": $title= "Gravação e corte a laser | Clicheria Voluntários"; $description= "Está em busca de Gravação e corte a laser? Conte com a que é especialista e oferece as melhores opções para quem busca por qualidade!"; break;
case "contato": $title= "Contato | Clicheria Voluntários"; $description= "Entre em contato com a Clicheria Voluntários e tenha o que há de melhor na gravação de clichês. Estamos aguardando por você. "; break;
case "empresa-de-cliches-na-zona-norte": $title= "Empresa de cliches na zona norte | Clicheria Voluntários"; $description= "Está em busca de Empresa de cliches na zona norte? Conte com a Clicheria Voluntários que é especialista e oferece as melhores opções para quem busca por qualidade!"; break;
case "clicheria-no-tucuruvi": $title= "Clicheria no tucuruvi | Clicheria Voluntários"; $description= "Procurando por Clicheria no tucuruvi? A Clicheria Voluntários conta com anos de experiência para oferecer o melhor custo-benefício do mercado!"; break;
case "cliche-de-fotopolimero": $title= "Cliche de fotopolimero | Clicheria Voluntários"; $description= "Precisando de Cliche de fotopolimero? A Clicheria Voluntários é uma das melhores empresas nesse segmento! Clique aqui para entrar em contato."; break;
case "cliches-para-alta-frequencia": $title= "Cliches para alta frequencia | Clicheria Voluntários"; $description= "Precisa de Cliches para alta frequencia? Só na Clicheria Voluntários você encontra as melhores e mais completas opções de produtos. Clique aqui e confira."; break;
case "cliche-em-zinco": $title= "Cliche em zinco | Clicheria Voluntários"; $description= "Se você busca por Cliche em zinco, com a Clicheria Voluntários você encontra o melhor que o mercado oferece. Clique para saber mais!"; break;
case "cliches-para-relevo": $title= "Cliches para relevo | Clicheria Voluntários"; $description= "Se está procurando por Cliches para relevo, aqui na Clicheria Voluntários você tem acesso as melhores opções do mercado! Clique e confira."; break;
case "cliches-para-hot-stamping": $title= "Cliches para hot stamping | Clicheria Voluntários"; $description= "Se precisa de Cliches para hot stamping, a Clicheria Voluntários oferece o que há de mais moderno e qualificado para atender a sua necessidade. Clique aqui para saber mais"; break;
case "cliche-em-magnesio": $title= "Cliche em magnesio | Clicheria Voluntários"; $description= "Está precisando de Cliche em magnesio? Só com a Clicheria Voluntários você tem acesso ao que há de melhor no segmento com preços acessíveis. Clique para saber mais"; break;
case "empresa-de-cliches-em-sp": $title= "Empresa de cliches em sp | Clicheria Voluntários"; $description= "Se está em busca de Empresa de cliches em sp? Na Clicheria Voluntários você tem a sua disposição os melhores produtos para atender a sua necessidade."; break;
case "cliche-para-emborrachado": $title= "Cliche para emborrachado | Clicheria Voluntários"; $description= "Se está buscando por Cliche para emborrachado? Com a Clicheria Voluntários você encontra o que precisa para atender a sua necessidade. Entre em contato para saber mais!"; break;

?>